name: biblio
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  very_good_analysis: ^7.0.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  shared_preferences: ^2.3.5
  icons_launcher: ^3.0.0
  easy_localization: ^3.0.7
  flutter_verification_code: ^1.1.7

  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
    - assets/svg/
    - assets/icons/

  fonts:
    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/Avenir-Regular.otf
        - asset: assets/fonts/Avenir-Medium.otf
          weight: 700

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
  
icons_launcher:
  image_path: "assets/icons/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true